spring:
  application:
    name: taskflow-backend

  datasource:
    url: jdbc:postgresql://${TASKFLOW_DB_HOST:localhost}:${TASKFLOW_DB_PORT:5432}/${TASKFLOW_DB_NAME:taskFlow}
    username: ${TASKFLOW_DB_USERNAME}
    password: ${TASKFLOW_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${TASKFLOW_REDIS_HOST:localhost}
      port: ${TASKFLOW_REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-wait: 1000ms

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${TASKFLOW_JWT_SECRET}
  access-token-expiry-ms: ${TASKFLOW_JWT_ACCESS_EXPIRY_MS:900000}      # 15 min
  refresh-token-expiry-days: ${TASKFLOW_JWT_REFRESH_EXPIRY_DAYS:7}

app:
  cors:
    allowed-origins: ${TASKFLOW_CORS_ALLOWED_ORIGINS:http://localhost:4200}